INSERT INTO track (
    track_id,
    track_name,
    track_artist,
    track_album_name,
    track_album_id,
    track_album_release_date,
    playlist_name,
    playlist_id,
    playlist_genre,
    playlist_subgenre,
    danceability,
    energy,
    loudness,
    speechiness,
    acousticness,
    instrumentalness,
    liveness,
    valence,
    tempo,
    duration_ms
)
VALUES (
    'test321',
    'Test Song',
    'Test Artist',
    'Test Album',
    'album123',
    '2024-01-01',
    'Playlist A',
    'playlist123',
    'dance pop',
    'pop',
    0.75,
    0.85,
    -5.1,
    0.04,
    0.12,
    0.00,
    0.10,
    0.62,
    120.0,
    180000
);
